### ISSUE TITLE
SyntaxError: Named export 'OpenSeaStreamClient' not found.

### ISSUE THREAD

**Issue by AeroXi** [ProjectOpenSea/stream-js#86]
I installed the dependency and copied the code as in README:
`import { OpenSeaStreamClient } from '@opensea/stream-js';`
I got:
```
import { OpenSeaStreamClient } from '@opensea/stream-js';
         ^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'OpenSeaStreamClient' not found. The requested module '@opensea/stream-js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@opensea/stream-js';
const { OpenSeaStreamClient } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

Node.js v18.0.0
```
I tried to add   "type": "module" in package.json but it didn't work

**Comment by AeroXi** [comment]
> all so getting same error did you find a way to fix it?

fixed in https://github.com/ProjectOpenSea/stream-js/pull/89

**Comment by Meemaw** [comment]
Can you try again on the latest version -- 0.0.18?

**Comment by wong2** [comment]
0.0.18 still doesn't work. I'm using ESM with `.mjs` file extension.

**Comment by itsthedoom** [comment]
@AeroXi are you still running into issues?
